### ISSUE TITLE
Error: MCE just crashed, please report the following:

### ISSUE THREAD

**Issue by rapi3** [platomav/MCExtractor#10]
`-------[ MC Extractor v1.13.2 r52 ]-------

Welcome to Intel, AMD, VIA & Freescale Microcode Extractor

Input a filename or "filepath" or press Enter to list options

File:       None

Option(s):  

Error: MCE just crashed, please report the following:

Traceback (most recent call last):
  File "MCE.py", line 834, in <module>
    input_var = input('\nOption(s):  ')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Press enter to exit
Error in sys.excepthook:
Traceback (most recent call last):
  File "MCE.py", line 538, in show_exception_and_exit
    input(col_e + '\nPress enter to exit')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Original exception was:
Traceback (most recent call last):
  File "MCE.py", line 834, in <module>
    input_var = input('\nOption(s):  ')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing`

**Comment by platomav** [comment]
Please share more info on how the error can be reproduced.
