### ISSUE TITLE
Redirection not work

### ISSUE THREAD

**Issue by chupor3d** [platomav/MCExtractor#13]
But other thinkgs, that not work:
Previous version works with redirection: MCE1111.exe J01_0231.BIN >a.a
But this version not:
MCE115.exe J01_0231.BIN >a.a           or   MCE115.exe J01_0231.BIN -skip >a.a
Traceback (most recent call last):
  File "MCE.py", line 1179, in <module>
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
  File "c:\python\python36-32\lib\encodings\cp1250.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-84: character maps to <und
efined>

**Comment by platomav** [comment]
Read the README > C1. Compatibility

**Comment by chupor3d** [comment]
OK, i read C1, put setting in batch, but same error with using mce115.bat
@echo off
SET PYTHONIOENCODING=UTF-8 
MCE115.exe %1 -skip -exit >i.txt

**Comment by platomav** [comment]
It works just fine when using MCE.py script and not the frozen PyInstaller executable. For some reason PyInstaller ignores PYTHONIOENCODING variable but that's not related to MCE. If you can use the python script, then I suggest you do that. If you really must use the executable then find and comment out the line "pt.set_style(prettytable.BOX_CHARS)".

**Comment by platomav** [comment]
Added -redir parameter at MCE v1.16.0 (ba1990a)
