### ISSUE TITLE
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'

### ISSUE THREAD

**Issue by yeroca** [platomav/MCExtractor#14]
Error on Fedora 27:

```
-------[ MC Extractor v1.15.0 r61 ]-------

File (1/2): GenuineIntel.bin


Error: MCE just crashed, please report the following:

Traceback (most recent call last):
  File "/home/xxxx/MCExtractor/MCE.py", line 1012, in <module>
    pt, pt_empty = mc_table(col_names, True, 1)
  File "/home/xxxx/MCExtractor/MCE.py", line 728, in mc_table
    pt.set_style(prettytable.BOX_CHARS) # Comment out if UnicodeEncodeError
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'

```

**Comment by platomav** [comment]
Answer at issue #11

**Comment by yeroca** [comment]
Ah, ok.  Sorry, I only saw one active open issue.  I ended up just commenting out the line, and everything is working well... except that the MCE.py file is in DOS (cr/lf) format, and had to have its cr's removed to run properly.

Great tool!  Thank you.

**Comment by platomav** [comment]
Yes I use Windows, that's why. Thank you for using MCE.
