### ISSUE TITLE
problem with prettytable 0.7.2

### ISSUE THREAD

**Issue by pietrushnic** [platomav/MCExtractor#17]
Hi,
I'm trying to use MCExtrctor and getting this information:

```
root@debian:~/MCExtractor# python3.6 MCE.py 

Error: MCE just crashed, please report the following:

Traceback (most recent call last):
  File "MCE.py", line 828, in <module>
    mce_hdr()
  File "MCE.py", line 787, in mce_hdr
    hdr_pt,hdr_pt_empty = mc_table([], False, 1)
  File "MCE.py", line 731, in mc_table
    if not param.cli_redirect : pt.set_style(prettytable.BOX_CHARS)
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'
```

Since MCE requires Python3.6 I used [this instruction](https://unix.stackexchange.com/a/332658/44718) on my Debian.

**Comment by pietrushnic** [comment]
Sorry didn't checked answered questions: https://github.com/platomav/MCExtractor/issues/11
