### ISSUE TITLE
Running on Ubuntu 20.04 crashes

### ISSUE THREAD

**Issue by superm1** [platomav/MCExtractor#32]
Fresh Ubuntu 20.04 release.
Installed the following:

```
$ pip3 install colorama
Collecting colorama
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.3
$ pip3 install prettytable
Collecting prettytable
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13698 sha256=3607cfad1d2e933194da840b07be2a0d16ae5748b1fae5fe218e12ed70625ecd
  Stored in directory: /home/test/.cache/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee
Successfully built prettytable
Installing collected packages: prettytable
Successfully installed prettytable-0.7.2
```

Running with no arguments I receive this:
```
Error: MC Extractor crashed, please report the following:

Traceback (most recent call last):
  File "./MCE.py", line 943, in <module>
    mce_hdr()
  File "./MCE.py", line 904, in mce_hdr
    hdr_pt,hdr_pt_empty = mc_table([], False, 1)
  File "./MCE.py", line 846, in mc_table
    pt.set_style(prettytable.UNICODE_LINES)
AttributeError: module 'prettytable' has no attribute 'UNICODE_LINES'

**Comment by superm1** [comment]
Although I notice now that the readme says to get `pltable` not `prettytable`.  Uninstalling and switching gets the right stuff.  Feel free to close if you want.

**Comment by platomav** [comment]
Exactly, pltable
