### ISSUE TITLE
can't run MC Extractor | module not found - sqlite3

### ISSUE THREAD

**Issue by jak83A** [platomav/MCExtractor#69]
I can't run MC Extractor on Ubuntu 22.04

```
python3 MCE.py 

Traceback (most recent call last):
  File "/home/jakob/Documents/CPU-MICROCODES/MCExtractor-r299/MCE.py", line 41, in <module>
    import sqlite3
  File "/usr/local/lib/python3.13/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.13/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: **No module named '_sqlite3'**
```

i tried:

```
pip install sqlite3
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
```

```
sudo apt install sqlite3-doc

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  sqlite3-doc
0 upgraded, 1 newly installed, 0 to remove and 23 not upgraded.
Need to get 7.208 kB of archives.
After this operation, 27,7 MB of additional disk space will be used.
Get:1 http://de.archive.ubuntu.com/ubuntu jammy-updates/main amd64 sqlite3-doc all 3.37.2-2ubuntu0.3 [7.208 kB]
Fetched 7.208 kB in 1s (12,7 MB/s)    
Selecting previously unselected package sqlite3-doc.
(Reading database ... 358975 files and directories currently installed.)
Preparing to unpack .../sqlite3-doc_3.37.2-2ubuntu0.3_all.deb ...
Unpacking sqlite3-doc (3.37.2-2ubuntu0.3) ...
Setting up sqlite3-doc (3.37.2-2ubuntu0.3) ...
```

**Comment by platomav** [comment]
sqlite3 is a built-in python library. Check your python installation and make sure you're using currently supported/production versions.
